import type { KnowledgeEntry } from "../types";

export const SAFETY: readonly KnowledgeEntry[] = [
  {
    id: "safety.general-safety",
    topic: "Safety principles — what we can (and can’t) do online",
    category: "safety",
    explanation:
      "Online education can explain concepts, what to expect, and what questions to ask. It cannot replace clinician evaluation. We do not diagnose, prescribe, or provide individualized treatment plans online.",
    whatItHelpsWith: ["Understanding boundaries", "Reducing confusion about medical advice vs education"],
    whoItsFor: ["Anyone using the site’s chat or tools"],
    whoItsNotFor: ["Anyone seeking urgent medical guidance—seek urgent/emergency care when appropriate"],
    commonQuestions: ["Can you tell me if I’m a candidate?", "Can you tell me what dose I need?", "Is this medical advice?"],
    safetyNotes: [
      "No diagnosis, prescribing, dosing, or clearance online.",
      "If uncertain: book a consultation.",
      "If urgent symptoms occur: seek urgent/emergency care.",
    ],
    escalationTriggers: ["urgent", "severe", "trouble breathing", "vision", "chest pain", "stroke"],
    relatedTopics: ["safety.post-treatment-red-flags", "expectations.program-based-care"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "safety.why-consults-matter",
    topic: "Why consultations matter (education)",
    category: "safety",
    explanation:
      "A consult isn’t a sales step—it’s a safety step. Educationally, it’s where we review goals, medical history, expectations, and what’s realistic. That’s how responsible medical care is done.",
    whatItHelpsWith: ["Reducing pressure", "Building trust", "Understanding safety-first process"],
    whoItsFor: ["Anyone who feels nervous about booking", "People who want clarity before deciding"],
    whoItsNotFor: ["Anyone seeking medical clearance online"],
    commonQuestions: ["What happens in a consult?", "Do I have to commit?", "Can I just ask questions?"],
    safetyNotes: ["Booking is optional.", "No diagnosis or individualized advice online."],
    escalationTriggers: ["urgent symptoms", "severe symptoms"],
    relatedTopics: ["safety.general-safety", "expectations.program-based-care"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "safety.ai-education-only",
    topic: "Why AI is education-only on this site",
    category: "safety",
    explanation:
      "AI can help explain concepts and help you ask better questions. It cannot examine you, review your full history, or make medical decisions. That’s why we keep it education-only and recommend a consult for personal advice.",
    whatItHelpsWith: ["Setting expectations for the chat", "Preventing misuse of AI"],
    whoItsFor: ["Anyone using the Care Engine or mascot chat"],
    whoItsNotFor: ["Anyone seeking diagnosis, prescribing, or clearance online"],
    commonQuestions: ["Can AI tell me what to do?", "Can you tell me if I’m a candidate?", "Why can’t you give dosing?"],
    safetyNotes: ["No diagnosis/prescribing online.", "In-person consult is the correct next step for personal decisions."],
    escalationTriggers: ["emergency", "urgent", "severe symptoms", "trouble breathing", "vision"],
    relatedTopics: ["safety.general-safety", "safety.why-consults-matter"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "safety.consent-and-expectations",
    topic: "Consent & expectations (education)",
    category: "safety",
    explanation:
      "Responsible care includes informed consent: what a service is, what it helps with, what it doesn’t do, and what risks exist at a high level. Educationally, the goal is a calm, confident decision—not a rushed one.",
    whatItHelpsWith: ["Building trust", "Reducing anxiety", "Encouraging clarity over pressure"],
    whoItsFor: ["First-time clients", "People who want to feel in control"],
    whoItsNotFor: ["Anyone seeking medical decision-making online"],
    commonQuestions: ["What should I ask before booking?", "How do I know if it’s right for me?", "What if I’m unsure?"],
    safetyNotes: ["No guarantees online.", "Consult required for individualized recommendations."],
    escalationTriggers: ["panic", "severe symptoms"],
    relatedTopics: ["safety.why-consults-matter", "expectations.program-based-care"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "safety.post-treatment-red-flags",
    topic: "Post-treatment red flags — when to seek urgent care",
    category: "safety",
    explanation:
      "Some symptoms after treatment can be urgent. Educationally, red flags include breathing problems, swelling of tongue/throat, vision changes, severe/worsening pain, fever with infection signs, or skin color changes after filler. When in doubt, contact your provider and seek urgent care if severe.",
    whatItHelpsWith: ["Recognizing when not to self-reassure", "Knowing when to contact clinic vs urgent care"],
    whoItsFor: ["Anyone with post-treatment questions"],
    whoItsNotFor: ["Anyone needing diagnosis—this is education only"],
    commonQuestions: ["Is this normal?", "When should I call?", "What symptoms are urgent?"],
    safetyNotes: [
      "This is educational only—no diagnosis.",
      "If severe or rapidly worsening symptoms occur, seek urgent/emergency care now.",
    ],
    escalationTriggers: ["trouble breathing", "vision", "blanch", "dusky", "necrosis", "severe pain", "fever", "pus"],
    relatedTopics: ["aftercare.general-aftercare", "aftercare.filler-swelling-bruising"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
] as const;

