import type { KnowledgeEntry } from "../types";

export const AFTERCARE: readonly KnowledgeEntry[] = [
  {
    id: "aftercare.filler-swelling-bruising",
    topic: "Aftercare: filler swelling & bruising — what’s typical (education)",
    category: "aftercare",
    explanation:
      "After filler, swelling and bruising can happen. Educationally, swelling can be most noticeable in the first 24–72 hours and settle over 1–2 weeks. Early asymmetry is often swelling-related. Final assessment should wait until things settle.",
    whatItHelpsWith: ["Reducing post-treatment anxiety", "Knowing what’s typical vs what needs attention (education)"],
    whoItsFor: ["People who recently had filler and want education about healing timelines"],
    whoItsNotFor: ["Anyone with severe pain, vision changes, breathing symptoms, or skin color changes—seek urgent care"],
    commonQuestions: ["How long will swelling last?", "Is asymmetry normal early on?", "What should I avoid?"],
    safetyNotes: [
      "No diagnosis online.",
      "Red flags after filler include vision changes, severe pain, or skin color changes—seek urgent care and contact your provider.",
    ],
    escalationTriggers: ["vision", "blanch", "dusky", "severe pain", "trouble breathing", "hives", "fever"],
    relatedTopics: ["safety.post-treatment-red-flags", "expectations.filler-timeline"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "aftercare.bruising-basics",
    topic: "Bruising after treatment — basics (education)",
    category: "aftercare",
    explanation:
      "Bruising can happen after injections and some skin treatments. Educationally, it often changes color and fades over days to a couple of weeks. Severity varies by individual, medications, and treatment area.",
    whatItHelpsWith: ["Reducing anxiety", "Setting expectations for appearance changes"],
    whoItsFor: ["People with mild bruising after aesthetic treatments"],
    whoItsNotFor: ["Anyone with uncontrolled bleeding or severe symptoms—seek urgent care"],
    commonQuestions: ["How long will it last?", "Can I cover it with makeup?", "When should I call?"],
    safetyNotes: ["No medical advice online.", "If bruising is severe or you feel unwell, contact your provider."],
    escalationTriggers: ["uncontrolled bleeding", "severe pain", "faint", "chest pain"],
    relatedTopics: ["aftercare.general-aftercare", "safety.post-treatment-red-flags"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "aftercare.tenderness-basics",
    topic: "Tenderness after treatment — basics (education)",
    category: "aftercare",
    explanation:
      "Mild tenderness can be a normal short-term reaction after many treatments. Educationally, it should improve over time. If pain is severe, worsening, or paired with fever or spreading redness, contact your provider.",
    whatItHelpsWith: ["Reassurance without over-reassuring", "Knowing when to escalate"],
    whoItsFor: ["People with mild soreness after treatment"],
    whoItsNotFor: ["Anyone with severe/worsening symptoms or infection signs"],
    commonQuestions: ["Is soreness normal?", "How long should it last?", "When is it a red flag?"],
    safetyNotes: ["Education only. Severe or worsening symptoms require evaluation."],
    escalationTriggers: ["severe pain", "fever", "pus", "worsening redness spreading"],
    relatedTopics: ["safety.post-treatment-red-flags", "aftercare.general-aftercare"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "aftercare.fatigue-after-iv",
    topic: "Fatigue after IV therapy (education)",
    category: "aftercare",
    explanation:
      "Some people feel tired after an IV—especially if they were already run down. Educationally, rest, hydration, and following your provider’s guidance matter. If you feel faint, have chest pain, or trouble breathing, seek urgent care.",
    whatItHelpsWith: ["Setting expectations", "Knowing when to seek help"],
    whoItsFor: ["People who feel tired after a wellness visit"],
    whoItsNotFor: ["Anyone with severe symptoms—seek urgent care"],
    commonQuestions: ["Is it normal to feel tired?", "How long should it last?", "When should I call?"],
    safetyNotes: ["Education only; severe symptoms require urgent evaluation."],
    escalationTriggers: ["faint", "chest pain", "shortness of breath", "trouble breathing"],
    relatedTopics: ["iv.iv-therapy-basics", "safety.general-safety"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "aftercare.general-aftercare",
    topic: "Aftercare basics — why it matters (education)",
    category: "aftercare",
    explanation:
      "Aftercare exists to support comfort and reduce avoidable irritation. Educationally, the safest approach is to follow your provider’s written instructions and contact the clinic if something feels unusual or worsening.",
    whatItHelpsWith: ["Understanding the purpose of aftercare", "Knowing when to contact the clinic (education)"],
    whoItsFor: ["Anyone who wants education about post-treatment support"],
    whoItsNotFor: ["Anyone needing urgent medical care—seek urgent/emergency care if severe symptoms occur"],
    commonQuestions: ["What should I do if I’m worried?", "What symptoms are red flags?", "When should I call?"],
    safetyNotes: ["No diagnosis online.", "If severe or rapidly worsening symptoms occur, seek urgent care."],
    escalationTriggers: ["trouble breathing", "vision", "severe pain", "fever", "pus", "worsening redness spreading"],
    relatedTopics: ["safety.post-treatment-red-flags"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
] as const;

