import type { KnowledgeEntry } from "../types";

export const SKINCARE: readonly KnowledgeEntry[] = [
  {
    id: "skincare.skin-barrier",
    topic: "Skin barrier — why it matters (education)",
    category: "skincare",
    explanation:
      "The skin barrier is your skin’s protective function. Educationally, many ‘sensitivity’ and ‘irritation’ issues are about barrier disruption. Consistency, gentle routines, and avoiding over-treatment can support comfort and outcomes.",
    whatItHelpsWith: ["Reducing irritation (education)", "Understanding why product selection matters", "Setting expectations for gradual improvement"],
    whoItsFor: ["People with sensitivity, dryness, or irritation concerns", "People starting a new skincare routine"],
    whoItsNotFor: ["Anyone needing diagnosis of a rash or infection online"],
    commonQuestions: ["Why does my skin sting with products?", "How do I avoid overdoing actives?", "What should I ask in consult?"],
    safetyNotes: ["We can’t diagnose skin conditions online.", "Seek medical care for severe/worsening symptoms or signs of infection."],
    escalationTriggers: ["severe swelling", "hives", "trouble breathing", "fever", "pus", "worsening spreading redness"],
    relatedTopics: ["skincare.microneedling-basics", "skincare.chemical-peel-basics", "aftercare.general-aftercare"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "skincare.collagen-decline",
    topic: "Collagen decline over time (education)",
    category: "skincare",
    explanation:
      "Educationally, collagen and elastin support skin firmness and texture. Over time, production naturally slows, and sun exposure can speed visible changes. Many skin treatments focus on supporting collagen remodeling over weeks to months.",
    whatItHelpsWith: ["Setting expectations for gradual change", "Understanding why consistency matters"],
    whoItsFor: ["People exploring skin firmness, texture, or aging concerns"],
    whoItsNotFor: ["Anyone seeking guaranteed outcomes or timelines"],
    commonQuestions: ["Can I rebuild collagen?", "Why does it take time?", "Is one treatment enough?"],
    safetyNotes: ["Education only. The right approach depends on your skin and history."],
    escalationTriggers: ["infection", "fever", "severe symptoms"],
    relatedTopics: ["expectations.gradual-skin-timelines", "skincare.microneedling-basics"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "skincare.sun-damage",
    topic: "Sun damage (education) — why it matters",
    category: "skincare",
    explanation:
      "Educationally, sun exposure affects pigment, redness, texture, and collagen over time. Sun protection isn’t about perfection—it’s about consistency. Treatments can support improvement, but ongoing sun exposure can undo progress.",
    whatItHelpsWith: ["Understanding prevention vs correction", "Setting expectations for maintenance"],
    whoItsFor: ["People exploring tone, pigment, redness, or texture"],
    whoItsNotFor: ["Anyone seeking diagnosis of a skin lesion online"],
    commonQuestions: ["Do I still need sunscreen in winter?", "Why does pigment come back?", "Can treatments fix everything?"],
    safetyNotes: ["We can’t diagnose skin lesions online. Seek medical evaluation for concerning spots."],
    escalationTriggers: ["bleeding lesion", "rapidly changing mole", "severe symptoms"],
    relatedTopics: ["skincare.skin-barrier", "expectations.gradual-skin-timelines"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "skincare.medical-grade-vs-retail",
    topic: "Medical-grade vs retail skincare (education)",
    category: "skincare",
    explanation:
      "Educationally, ‘medical-grade’ is often a marketing term. What matters is evidence-informed ingredients, stable formulations, appropriate concentrations, and whether your skin barrier tolerates it. The best routine is the one you can use consistently.",
    whatItHelpsWith: ["Reducing hype", "Making skincare feel simpler"],
    whoItsFor: ["People overwhelmed by brands", "People with sensitive skin"],
    whoItsNotFor: ["Anyone seeking a personalized product prescription online"],
    commonQuestions: ["Is medical-grade real?", "Do I need expensive products?", "Why does my skin react?"],
    safetyNotes: ["Education only. Severe reactions require medical care."],
    escalationTriggers: ["hives", "trouble breathing", "severe swelling", "fever"],
    relatedTopics: ["comparisons.skincare-brands-conceptual", "skincare.skin-barrier"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "skincare.microneedling-basics",
    topic: "Microneedling (and RF microneedling) — basics",
    category: "skincare",
    explanation:
      "Microneedling is a procedure that creates controlled micro-injuries to support skin renewal. RF microneedling adds energy that can support collagen remodeling. Educationally, results are gradual and often discussed as part of a series, not an instant change.",
    whatItHelpsWith: ["Texture and pores (education)", "Skin quality over time (education)", "Expectation-setting about gradual change"],
    whoItsFor: ["People exploring skin texture/tone support", "People who want education-first timelines"],
    whoItsNotFor: ["Anyone seeking a guarantee of results", "Anyone needing individualized protocol selection online"],
    commonQuestions: ["How much downtime is typical?", "How many sessions do people do?", "When do results show?"],
    safetyNotes: ["Candidacy varies by skin type and history; consult required.", "Infection signs or severe symptoms require medical attention."],
    escalationTriggers: ["fever", "pus", "worsening redness spreading", "severe pain"],
    relatedTopics: ["aftercare.microneedling-aftercare", "expectations.gradual-skin-timelines"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "skincare.chemical-peel-basics",
    topic: "Chemical peels — basics",
    category: "skincare",
    explanation:
      "A chemical peel is a controlled exfoliation that supports skin tone and texture goals. Educationally, peel depth matters: some peels have little visible peeling; others have more downtime. Prep and aftercare support safety and comfort.",
    whatItHelpsWith: ["Tone/texture goals (education)", "Glow/clarity (education)", "Expectation setting about peeling and downtime"],
    whoItsFor: ["People exploring skin refresh options", "People who want education-first expectations"],
    whoItsNotFor: ["Anyone seeking a ‘best peel for me’ selection online"],
    commonQuestions: ["Will I peel?", "How do I prepare?", "How often can I do it?"],
    safetyNotes: ["Individual recommendations require consult.", "Severe reactions or infection signs require medical care."],
    escalationTriggers: ["severe swelling", "hives", "trouble breathing", "fever", "pus"],
    relatedTopics: ["aftercare.general-aftercare", "skincare.skin-barrier"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
] as const;

