import type { KnowledgeEntry } from "../types";

export const INJECTABLES: readonly KnowledgeEntry[] = [
  {
    id: "injectables.botox-basics",
    topic: "Botox / Dysport / Jeuveau (neuromodulators) — basics",
    category: "injectables",
    explanation:
      "Neuromodulators are prescription medications used in-office to temporarily relax specific facial muscles. Educationally, they’re often explored to soften expression lines while keeping you looking like you. Technique, anatomy, and expectation setting matter more than brand hype.",
    whatItHelpsWith: [
      "Softening expression lines (education)",
      "A refreshed look without changing identity (education)",
      "Building a maintenance mindset (education)",
    ],
    whoItsFor: [
      "People who want subtle, natural-looking softening of expression lines",
      "People who prefer a consult-first, safety-first approach",
      "People who want clear expectations and gradual change",
    ],
    whoItsNotFor: [
      "Anyone seeking individualized dosing or unit recommendations online",
      "Anyone seeking medical clearance online (requires consult)",
      "Anyone with urgent symptoms (seek urgent/emergency care)",
    ],
    commonQuestions: [
      "Botox vs Dysport vs Jeuveau — what’s the difference?",
      "When do results kick in?",
      "How long do results last?",
      "Will I look frozen?",
    ],
    safetyNotes: [
      "This is educational only—no diagnosis, prescriptions, or individualized medical advice.",
      "Eligibility depends on medical history, medications, and goals—confirmed in consult.",
      "If severe symptoms occur (breathing difficulty, vision changes, severe swelling), seek urgent/emergency care.",
    ],
    escalationTriggers: [
      "pregnant",
      "breastfeeding",
      "neuromuscular",
      "blood thinner",
      "allergic reaction",
      "trouble breathing",
      "vision changes",
      "severe headache",
    ],
    relatedTopics: ["injectables.botox-vs-dysport-vs-jeuveau", "expectations.neuromodulator-timeline", "safety.general-safety"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.neuromodulators-how-they-work",
    topic: "How neuromodulators work (high-level)",
    category: "injectables",
    explanation:
      "Educationally, neuromodulators reduce muscle signaling in very specific areas. That can soften expression lines formed by repeated movement. They don’t “fill” volume and they don’t tighten skin like a surgical lift.",
    whatItHelpsWith: ["Understanding the mechanism at a high level", "Knowing what the treatment does vs does not do"],
    whoItsFor: ["People who want a clear, non-technical explanation", "First-timers who feel nervous"],
    whoItsNotFor: ["Anyone seeking personalized dosing, units, or placement online"],
    commonQuestions: ["Does it paralyze my face?", "Will it change my personality?", "Will it lift my brows?"],
    safetyNotes: [
      "This is educational only—individualized planning requires a consult.",
      "If you have complex medical history, discuss it with your provider.",
    ],
    escalationTriggers: ["pregnant", "breastfeeding", "neuromuscular", "allergy", "trouble breathing"],
    relatedTopics: ["injectables.botox-basics", "expectations.neuromodulator-timeline", "safety.general-safety"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.neuromodulators-what-they-dont-do",
    topic: "What neuromodulators do NOT do (education)",
    category: "injectables",
    explanation:
      "Neuromodulators can soften expression lines, but they don’t replace skin-quality care. They won’t fix sun damage, texture, large pores, or deep volume loss on their own. Many people pair them with skincare and skin treatments over time.",
    whatItHelpsWith: ["Setting realistic expectations", "Reducing disappointment from unrealistic goals"],
    whoItsFor: ["People comparing options for lines vs skin texture", "People building a long-term plan mindset"],
    whoItsNotFor: ["Anyone seeking guaranteed results"],
    commonQuestions: ["Will it erase deep lines?", "Does it help pores?", "Do I need something else too?"],
    safetyNotes: ["Education only; consult required for personalized recommendations."],
    escalationTriggers: ["complication", "severe symptoms"],
    relatedTopics: ["skincare.skin-barrier", "skincare.microneedling-basics", "expectations.neuromodulator-timeline"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.neuromodulators-myths",
    topic: "Neuromodulator myths (education)",
    category: "injectables",
    explanation:
      "A few common myths: 1) “You’ll look frozen.” Not if the goal is natural movement and dosing is conservative. 2) “It’s addictive.” People may like the results, but it’s not a chemical dependency. 3) “Only older people do it.” Many people explore it for prevention or subtle refresh.",
    whatItHelpsWith: ["Reducing fear", "Setting a calm, realistic mindset"],
    whoItsFor: ["First-timers who feel anxious", "People worried about looking unnatural"],
    whoItsNotFor: ["Anyone seeking medical advice online"],
    commonQuestions: ["Will I look fake?", "Is it safe long-term?", "Is it only for older clients?"],
    safetyNotes: ["No guarantees; outcomes vary.", "Consult required for individualized decisions."],
    escalationTriggers: ["allergy", "pregnant", "breastfeeding", "neuromuscular"],
    relatedTopics: ["injectables.botox-basics", "safety.general-safety", "expectations.neuromodulator-timeline"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.neuromodulators-why-results-vary",
    topic: "Why neuromodulator results vary (education)",
    category: "injectables",
    explanation:
      "Educationally, results can vary due to anatomy, muscle strength, metabolism, and your goals (subtle vs stronger change). Timing of touch-ups and maintenance also varies. The safest approach is expectation setting and a consult-first plan.",
    whatItHelpsWith: ["Understanding variability", "Reducing anxiety if results feel different than expected"],
    whoItsFor: ["People comparing themselves to others", "Returning clients noticing changes over time"],
    whoItsNotFor: ["Anyone seeking dosing or protocol online"],
    commonQuestions: ["Why didn’t it last as long?", "Why does it feel different this time?", "Do I need more units?"],
    safetyNotes: ["No dosing or clearance online.", "Discuss your history and goals during consult."],
    escalationTriggers: ["complication", "vision", "severe headache"],
    relatedTopics: ["expectations.neuromodulator-timeline", "safety.general-safety"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.botox-vs-dysport-vs-jeuveau",
    topic: "Botox vs Dysport vs Jeuveau — how they differ (high-level)",
    category: "comparisons",
    explanation:
      "All three are neuromodulators used for similar goals. Differences are often discussed at a high level as formulation/brand differences and how an individual responds. Educationally, what matters most is assessment, technique, and expectation setting—not chasing a brand.",
    whatItHelpsWith: ["Understanding categories without over-focusing on brand", "Setting expectations before booking"],
    whoItsFor: ["People comparing neuromodulator options", "People who want a calm, non-sales explanation"],
    whoItsNotFor: ["Anyone seeking a recommendation for their face online", "Anyone seeking dosing/units online"],
    commonQuestions: ["Which is best?", "Do they last different lengths?", "Do they kick in faster?"],
    safetyNotes: [
      "We don’t recommend a specific product for you online; selection is made in consult.",
      "No dosing/units/protocols here.",
    ],
    escalationTriggers: ["complication", "allergy", "pregnant", "breastfeeding", "vision"],
    relatedTopics: ["injectables.botox-basics", "expectations.neuromodulator-timeline", "safety.general-safety"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.filler-ha-basics",
    topic: "Hyaluronic acid (HA) filler — basics (education)",
    category: "injectables",
    explanation:
      "Many common fillers are made with hyaluronic acid (HA), a substance your body also has naturally. Educationally, HA fillers are used to support shape, hydration, and balance. The plan is individualized based on anatomy and goals.",
    whatItHelpsWith: ["Understanding what HA means", "Reducing fear of “foreign” materials (education)"],
    whoItsFor: ["People considering fillers who want plain-language clarity"],
    whoItsNotFor: ["Anyone seeking product selection or volume planning online"],
    commonQuestions: ["Is HA safe?", "Is it permanent?", "Does it migrate?"],
    safetyNotes: [
      "Education only; candidacy and product selection are decided in consult.",
      "If you have severe symptoms after treatment, seek urgent care.",
    ],
    escalationTriggers: ["vision", "severe pain", "dusky", "blanch", "trouble breathing", "hives"],
    relatedTopics: ["injectables.filler-basics", "expectations.filler-timeline", "safety.post-treatment-red-flags"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.filler-natural-vs-dramatic",
    topic: "Natural vs dramatic filler outcomes (education)",
    category: "injectables",
    explanation:
      "Educationally, ‘natural’ results usually come from conservative changes that match your facial proportions. ‘Dramatic’ results tend to be more noticeable changes. Neither is “right” or “wrong”—what matters is your comfort level, safety, and expectation setting.",
    whatItHelpsWith: ["Clarifying your preference", "Reducing fear of looking overdone"],
    whoItsFor: ["People unsure how much change they want", "People who want to feel in control of the plan"],
    whoItsNotFor: ["Anyone seeking a guarantee of a specific look"],
    commonQuestions: ["Can filler look natural?", "How do I avoid being overdone?", "What should I say at consult?"],
    safetyNotes: ["No guarantees online.", "In-person assessment is required for planning."],
    escalationTriggers: ["complication", "infection", "vision", "severe pain"],
    relatedTopics: ["aesthetics.facial-balance", "injectables.filler-basics", "expectations.filler-timeline"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.filler-reversibility",
    topic: "Filler reversibility (high-level education)",
    category: "injectables",
    explanation:
      "Some HA fillers can be dissolved if needed. Educationally, that doesn’t mean reversibility is a “plan”—it’s a safety tool. Decisions about dissolving are clinical and require evaluation.",
    whatItHelpsWith: ["Reducing fear", "Understanding that safety protocols exist"],
    whoItsFor: ["People anxious about being ‘stuck’ with results"],
    whoItsNotFor: ["Anyone seeking guidance on dissolving online"],
    commonQuestions: ["Can it be reversed?", "When would dissolving be used?", "Is dissolving risky?"],
    safetyNotes: ["No individualized medical advice online.", "Urgent symptoms require urgent care."],
    escalationTriggers: ["vision", "severe pain", "skin turning", "dusky", "blanch"],
    relatedTopics: ["safety.post-treatment-red-flags", "injectables.filler-basics"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
  {
    id: "injectables.filler-basics",
    topic: "Dermal fillers — basics",
    category: "injectables",
    explanation:
      "Dermal fillers are in-office injectable products often used to support facial balance—restoring volume, refining contour, or enhancing features. Education-first framing focuses on harmony and proportion, not ‘more.’ Early swelling can distort the look; final assessment happens after settling.",
    whatItHelpsWith: ["Facial balance concepts (education)", "Volume/contour support (education)", "Expectation setting about swelling and settling"],
    whoItsFor: ["People who want subtle enhancement and facial harmony", "People who prefer consult-first planning"],
    whoItsNotFor: ["Anyone seeking a specific product/volume plan online", "Anyone with urgent post-procedure symptoms (seek care)"],
    commonQuestions: ["How long does swelling last?", "Can it look natural?", "How long do fillers last?", "Can filler be dissolved?"],
    safetyNotes: [
      "This is educational only. Individualized planning requires in-person assessment.",
      "Certain symptoms after filler can be urgent (vision changes, severe pain, skin color changes). Seek urgent care and contact your provider.",
    ],
    escalationTriggers: ["vision", "skin blanching", "dusky", "severe pain", "trouble breathing", "hives", "fever"],
    relatedTopics: ["aftercare.filler-swelling-bruising", "safety.post-treatment-red-flags", "expectations.filler-timeline"],
    updatedAt: "2026-01-29T00:00:00.000Z",
    version: 1,
  },
] as const;

